# Generated by Django 5.0.1 on 2024-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0002_alter_trainer_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="image_up",
            field=models.ImageField(null=True, upload_to="trainers_images/"),
        ),
    ]
