# Generated by Django 5.0.1 on 2024-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0003_trainer_image_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("trainer", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=400)),
            ],
        ),
    ]
